import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import GlobalState from "@/context";
import NextThemeProvider from "@/theme-provider";
import CommonLayout from "@/components/CommonLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Flood Early Warning",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <html lang="en">
    //   <head>
    //     {/* Tambahkan tag <head> jika perlu, seperti meta tags, link tags, dll */}
    //   </head>
    //   <body className={inter.className}>
    //     {/* ===== Page Wrapper Start ===== */}
    //     <div className="flex">
    //       {/* ===== Sidebar Start ===== */}
    //       <Sidebar />
    //       {/* ===== Sidebar End ===== */}

    //       {/* ===== Content Area Start ===== */}
    //       <div className="relative flex flex-1 flex-col lg:ml-72.5">
    //         {/* ===== Header Start ===== */}
    //         <Navbar />
    //         {/* ===== Header End ===== */}

    //         {/* ===== Main Content Start ===== */}
    //         <main>
    //           <div className="mx-auto max-w-screen-2xl p-4 md:p-6 2xl:p-10">
    //             {children}
    //           </div>
    //         </main>
    //         {/* ===== Main Content End ===== */}
    //       </div>
    //       {/* ===== Content Area End ===== */}
    //     </div>
    //     {/* ===== Page Wrapper End ===== */}
    //   </body>
    // </html>
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
          <NextThemeProvider>
            <CommonLayout>{children}</CommonLayout>
          </NextThemeProvider>
        </GlobalState>
      </body>
    </html>
  );
}
